"""add field coordinates

Revision ID: 03d165a6e04a
Revises: 7d7c09820935
Create Date: 2026-09-16 17:50:43.219702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d165a6e04a'
down_revision: Union[str, Sequence[str], None] = '7d7c09820935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('fields', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'longitude')
    op.drop_column('fields', 'latitude')
    # ### end Alembic commands ###
