"""create crops table

Revision ID: 167ac6e9ee79
Revises: 733d8bcbf959
Create Date: 2026-09-01 15:44:25.957991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167ac6e9ee79'
down_revision: Union[str, Sequence[str], None] = '733d8bcbf959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('crop_type', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('planting_date', sa.Date(), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'HARVESTED', 'FAILED', name='cropstatus'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_field_id'), 'crops', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crops_field_id'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
