"""create agricultural observations

Revision ID: 7d7c09820935
Revises: 167ac6e9ee79
Create Date: 2026-09-08 13:46:25.928074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7c09820935'
down_revision: Union[str, Sequence[str], None] = '167ac6e9ee79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agricultural_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('observation_type', sa.Enum('SOIL_MOISTURE', 'SOIL_TEMPERATURE', 'SOIL_PH', 'NITROGEN', 'PHOSPHORUS', 'POTASSIUM', 'AIR_TEMPERATURE', 'AIR_HUMIDITY', 'RAINFALL', 'WIND_SPEED', 'LIGHT_INTENSITY', name='observationtype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'WEATHER_API', 'SOIL_API', 'SATELLITE', 'IOT_SENSOR', name='observationsource'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agricultural_observations_field_id'), 'agricultural_observations', ['field_id'], unique=False)
    op.create_index(op.f('ix_agricultural_observations_observation_type'), 'agricultural_observations', ['observation_type'], unique=False)
    op.create_index(op.f('ix_agricultural_observations_observed_at'), 'agricultural_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_agricultural_observations_source'), 'agricultural_observations', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agricultural_observations_source'), table_name='agricultural_observations')
    op.drop_index(op.f('ix_agricultural_observations_observed_at'), table_name='agricultural_observations')
    op.drop_index(op.f('ix_agricultural_observations_observation_type'), table_name='agricultural_observations')
    op.drop_index(op.f('ix_agricultural_observations_field_id'), table_name='agricultural_observations')
    op.drop_table('agricultural_observations')
    # ### end Alembic commands ###
