"""add alerts

Revision ID: 908208745623
Revises: 03d165a6e04a
Create Date: 2026-09-30 13:36:25.238902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908208745623'
down_revision: Union[str, Sequence[str], None] = '03d165a6e04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.Enum('IRRIGATION', 'WEATHER', 'DISEASE', 'CROP_HEALTH', 'SYSTEM', name='alerttype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='alertpriority'), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ACKNOWLEDGED', 'EXPIRED', name='alertstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_crop_id'), 'alerts', ['crop_id'], unique=False)
    op.create_index(op.f('ix_alerts_deduplication_key'), 'alerts', ['deduplication_key'], unique=False)
    op.create_index(op.f('ix_alerts_expires_at'), 'alerts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_alerts_farm_id'), 'alerts', ['farm_id'], unique=False)
    op.create_index(op.f('ix_alerts_field_id'), 'alerts', ['field_id'], unique=False)
    op.create_index(op.f('ix_alerts_priority'), 'alerts', ['priority'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_priority'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_field_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_farm_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_expires_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_deduplication_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_crop_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
