"""Track refresh token rotation

Revision ID: b5d34300c6e6
Revises: 3e88995abf36
Create Date: 2026-08-21 15:54:41.660749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d34300c6e6'
down_revision: Union[str, Sequence[str], None] = '3e88995abf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_sessions', sa.Column('replaced_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'refresh_sessions', 'refresh_sessions', ['replaced_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='foreignkey')
    op.drop_column('refresh_sessions', 'replaced_by_id')
    # ### end Alembic commands ###
